# Generated by Django 5.2.1 on 2025-05-28 14:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfiles',
            name='file_location',
            field=models.FileField(upload_to='user_uploads/'),
        ),
        migrations.RemoveField(
            model_name='uploadedfiles',
            name='shared_to',
        ),
        migrations.AddField(
            model_name='uploadedfiles',
            name='shared_to',
            field=models.ManyToManyField(related_name='shared_files', to=settings.AUTH_USER_MODEL),
        ),
    ]
