# Generated by Django 5.2.1 on 2025-05-28 15:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('storage', '0002_alter_uploadedfiles_file_location_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfiles',
            name='shared_to',
        ),
        migrations.AddField(
            model_name='uploadedfiles',
            name='shared_groups',
            field=models.ManyToManyField(blank=True, related_name='shared_files_groups', to='auth.group'),
        ),
        migrations.AddField(
            model_name='uploadedfiles',
            name='shared_users',
            field=models.ManyToManyField(blank=True, related_name='shared_files_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
