# Generated by Django 5.2.1 on 2025-05-29 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_remove_uploadedfiles_shared_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfiles',
            name='file_location',
        ),
        migrations.AddField(
            model_name='uploadedfiles',
            name='file_key',
            field=models.TextField(blank=True),
        ),
    ]
