# Generated by Django 5.2.1 on 2025-05-29 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_remove_uploadedfiles_file_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileChunks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_name', models.CharField(max_length=300)),
                ('chunk_file', models.FileField(upload_to='user_uploads/file_chunks/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('main_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.uploadedfiles')),
            ],
            options={
                'unique_together': {('main_file', 'chunk_name')},
            },
        ),
    ]
