# Generated by Django 5.2.1 on 2025-05-29 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_filechunks'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='filechunks',
            unique_together={('main_file', 'chunk_file')},
        ),
        migrations.RemoveField(
            model_name='uploadedfiles',
            name='file_key',
        ),
        migrations.AddField(
            model_name='filechunks',
            name='aes_key',
            field=models.BinaryField(blank=True),
        ),
        migrations.AddField(
            model_name='filechunks',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uploadedfiles',
            name='file_hash',
            field=models.CharField(max_length=128),
        ),
        migrations.RemoveField(
            model_name='filechunks',
            name='chunk_name',
        ),
    ]
