# Generated by Django 5.2.1 on 2025-05-29 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_alter_filechunks_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfiles',
            name='title_for_uploading',
        ),
    ]
