# Generated by Django 5.2.1 on 2025-06-03 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0007_remove_uploadedfiles_title_for_uploading'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfiles',
            name='file_description',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
