# Generated by Django 5.2.1 on 2025-06-03 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0008_uploadedfiles_file_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfiles',
            name='file_description',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
