# Generated by Django 5.2.1 on 2025-06-05 16:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0010_fileactivitylog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileactivitylog',
            name='file_id',
        ),
        migrations.AddField(
            model_name='fileactivitylog',
            name='file_uid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfiles',
            name='file_uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
